Support `x-tracking-request-id` header to have separate parallel data requests.
AldiDigitalServices/phpMockCollector pull request #4
Opened 2022-07-14 18:48 UTC by zeetabit

- Introduced `X-Tracking-Request-Id` header.
- Introduced concurrent request handling support by dividing data by introduced header.
- Introduced unit tests with new header.

2022-07-17 06:46 UTC, DanielHansmannAldi requested changes
I’m a little bit confused about the Methode and variable naming.

If I get the Idea right it is to enable parallel requests of the same kind and therefore add a requestID. (What I totally like by the wax 👍)

so can we please find a consistent naming for this.

Method is confusing because of HTTP Method

2022-07-18 15:51 UTC, zeetabit commented
@DanielHansmannAldi done, please review one more time.

2022-07-19 09:06 UTC, DanielHansmannAldi commented on src/phpMockServer.php
> +        $requestId = $this->getRequestId();
You repeat yourself with line 210

2022-07-19 09:06 UTC, DanielHansmannAldi commented on src/phpMockServer.php
> +        $requestId = $this->getRequestId();
You repeat yourself with line 210

2022-07-19 09:06 UTC, DanielHansmannAldi commented on src/rules/preselectionRuleImplementation.php
> +    protected static function readPreselection($methode, $xMockRequestId, $path)
Why Donnie make this a breaking change?
Why not move to the end and make it optional?

2022-07-19 15:51 UTC, zeetabit commented on src/phpMockServer.php
> +        $requestId = $this->getRequestId();
removed duplication

2022-07-19 15:54 UTC, zeetabit commented
@DanielHansmannAldi done, please review one more time.

2022-07-21 08:29 UTC, DanielHansmannAldi approved these changes

2022-07-21 08:29 UTC, merged